import React from "react";
import CategoryBanner from "./categoryBanner";
import Chandeliers from "./Chandeliers";
import { useParams } from "react-router-dom";

import ShowCategoryWise from "./ShowCategoryWise";

const products = [
  {
    discontpersentage:"5",name: "Full Interior Desging",
    price: "35,00 ",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/full-home-interior.jpg",
  },
  {
    discontpersentage:"5",name: "Wardrobe",
    price: "28,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/wardrobe.jpg",
  },
  {
    discontpersentage:"5",name: "Kitchen",
    price: "40,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/kitchen.jpg",
  },
  {
    discontpersentage:"5",name: "Living Room",
    price: "22,500.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/living-room.jpg",
  },
  {
    discontpersentage:"5",name: "False Celling",
    price: "50,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/false-ceiling.jpg",
  },
  {
    discontpersentage:"5",name: "Interior Lighting",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/interior-lighting.jpg",
  },
  {
    discontpersentage:"5",name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Weekend Vibes (Gold) Chandelier",
    price: "5,600.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl113-10001_21__1.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Touch The Clouds (Small, Gold) Round Crystal Chandelier",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl79-10002_16_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Summer Days (Gold, 3 Color LED) Chandelier",
    price: "8,400.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl225-10002_11_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Never Seen Forever (Large, Gold, Dimmable LED with Remote Control) Chandelier",
    price: "4,300.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl170-10005_19_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage:"5",name: "Modern LED Wall Light",
    price: "5,000.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image12.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Wall Sconce",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image13.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Wall Lamp",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image14.jpg",
  },
  {
    discontpersentage:"5",name: "Art Deco Wall Light",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image15.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Table Lamp",
    price: "3,200.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image16.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Desk Lamp",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image17.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Table Lamp",
    price: "4,000.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image18.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Table Lamp",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image19.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Desk Lamp",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image20.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Floor Lamp",
    price: "7,000.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image21.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Floor Lamp",
    price: "6,500.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image22.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Floor Lamp",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image23.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Floor Lamp",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image24.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Floor Lamp",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image25.jpg",
  },
  {
    discontpersentage:"5",name: "Decorative Vase Set",
    price: "2,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image26.jpg",
  },
  {
    discontpersentage:"5",name: "Abstract Wall Art",
    price: "5,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image27.jpg",
  },
  {
    discontpersentage:"5",name: "Decorative Mirror",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image28.jpg",
  },
  {
    discontpersentage:"5",name: "Decorative Sculpture",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image29.jpg",
  },
  {
    discontpersentage:"5",name: "Decorative Candle Holder",
    price: "2,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image30.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Ceiling Light",
    price: "12,000.00",
    delivery: "Free Delivery",
    category: "Ceiling Lights",
    img: "path/to/image31.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Ceiling Light",
    price: "10,500.00",
    delivery: "Free Delivery",
    category: "Ceiling Lights",
    img: "path/to/image32.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Ceiling Light",
    price: "13,800.00",
    delivery: "Free Delivery",
    category: "Ceiling Lights",
    img: "path/to/image33.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Ceiling Light",
    price: "15,200.00",
    delivery: "Free Delivery",
    category: "Ceiling Lights",
    img: "path/to/image34.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Ceiling Light",
    price: "14,000.00",
    delivery: "Free Delivery",
    category: "Ceiling Lights",
    img: "path/to/image35.jpg",
  },
  {
    discontpersentage:"5",name: "Outdoor Wall Light",
    price: "6,000.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image36.jpg",
  },
  {
    discontpersentage:"5",name: "Outdoor Post Light",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image37.jpg",
  },
  {
    discontpersentage:"5",name: "Outdoor Hanging Lantern",
    price: "9,500.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image38.jpg",
  },
  {
    discontpersentage:"5",name: "Outdoor Path Light",
    price: "5,200.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image39.jpg",
  },
  {
    discontpersentage:"5",name: "Outdoor Security Light",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image40.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Ceiling Fan",
    price: "12,500.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image41.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Ceiling Fan",
    price: "10,800.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image42.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Ceiling Fan",
    price: "13,300.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image43.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Ceiling Fan",
    price: "15,500.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image44.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Ceiling Fan",
    price: "14,800.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image45.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Vanity Light",
    price: "8,000.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image46.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Vanity Light",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image47.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Vanity Light",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image48.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Vanity Light",
    price: "10,500.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image49.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Vanity Light",
    price: "8,800.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image50.jpg",
  },
  {
    discontpersentage:"5",name: "Kind To The Mind (Large, Green, Blue) Clear Glass Chandelier",
    price: "35,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl215-10002_5_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage:"5",name: "Mixed Emotions (Large, Chrome, Amber, White) Clear Glass Chandelier",
    price: "28,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl217-10003_10_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage:"5",name: "Queen's Necklace (Medium, Rose Gold) Crystal Chandelier",
    price: "40,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl23-10004_3_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage:"5",name: "Watch the Throne (Large, Horizontal, Gold) Crystal Chandelier",
    price: "22,500.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10004_01_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage:"5",name: "Made In Heaven (Large, Green, White) Glass Chandelier",
    price: "50,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10003_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage:"5",name: "Industrial Iron Pendant",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image56.jpg",
  },
  {
    discontpersentage:"5",name: "Minimalist White Pendant",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image57.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Black Pendant",
    price: "5,600.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image58.jpg",
  },
  {
    discontpersentage:"5",name: "Glass Globe Pendant",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image59.jpg",
  },
  {
    discontpersentage:"5",name: "Bronze Finish Pendant",
    price: "8,400.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image60.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Wall Light",
    price: "4,300.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image61.jpg",
  },
  {
    discontpersentage:"5",name: "Modern LED Wall Light",
    price: "5,000.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image62.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Wall Sconce",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image63.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Wall Lamp",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image64.jpg",
  },
  {
    discontpersentage:"5",name: "Art Deco Wall Light",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image65.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Table Lamp",
    price: "3,200.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image66.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Desk Lamp",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image67.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Table Lamp",
    price: "4,000.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image68.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Table Lamp",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image69.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Desk Lamp",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image70.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Floor Lamp",
    price: "7,000.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image71.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Floor Lamp",
    price: "6,500.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image72.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Floor Lamp",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image73.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Floor Lamp",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image74.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Floor Lamp",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image75.jpg",
  },
  {
    discontpersentage:"5",name: "Modern Curtain",
    price: "2,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image76.jpg",
  },
  {
    discontpersentage:"5",name: "Classic Curtain",
    price: "2,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image77.jpg",
  },
  {
    discontpersentage:"5",name: "Rustic Curtain",
    price: "3,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image78.jpg",
  },
  {
    discontpersentage:"5",name: "Vintage Curtain",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image79.jpg",
  },
  {
    discontpersentage:"5",name: "Industrial Curtain",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "path/to/image80.jpg",
  },
];

const categoryDetails = ({category}) => {
  const { name } = useParams();

  const selectname = category || name;

  const filteredProducts = products.filter(
    (product) => product.category.toLowerCase() === selectname .toLowerCase()
  );
  // Add more categories as needed

  return (
    <div>
      
      
     
      {name?(<><CategoryBanner title="Our Products" />
      <Chandeliers name={selectname } /> </> 
    ):null}
     
      
      <ShowCategoryWise products={filteredProducts} />
      {/* <ShowCategoryWise title="Pendants" products={pendants} />
        <ShowCategoryWise title="Wall Lights" products={wallLights} /> */}
      {/* Add more categories as needed */}
    </div>
  );
};

export default categoryDetails;
