import React from "react";
import CategoryBanner from "./categoryBanner";
import Chandeliers from "./Chandeliers";
import { useParams } from "react-router-dom";

import ShowCategoryWise from "./ShowCategoryWise";

const products = [
  {
    discontpersentage: "5",
    name: "Full Interior Desging",
    price: "35,00 ",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/full-home-interior.jpg",
  },
  {
    discontpersentage: "5",
    name: "Wardrobe",
    price: "28,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/wardrobe.jpg",
  },
  {
    discontpersentage: "5",
    name: "Kitchen",
    price: "40,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/kitchen.jpg",
  },
  {
    discontpersentage: "5",
    name: "Living Room",
    price: "22,500.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/living-room.jpg",
  },
  {
    discontpersentage: "5",
    name: "False Celling",
    price: "50,000.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/false-ceiling.jpg",
  },
  {
    discontpersentage: "5",
    name: "Interior Lighting",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://homelineteam.com/images/products/interior-design/interior-lighting.jpg",
  },
  {
    discontpersentage: "5",
    name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Weekend Vibes (Gold) Chandelier",
    price: "5,600.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl113-10001_21__1.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Touch The Clouds (Small, Gold) Round Crystal Chandelier",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl79-10002_16_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Summer Days (Gold, 3 Color LED) Chandelier",
    price: "8,400.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl225-10002_11_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Never Seen Forever (Large, Gold, Dimmable LED with Remote Control) Chandelier",
    price: "4,300.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl170-10005_19_.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Touch The Clouds (Medium, Rectangular, Gold) Crystal Chandelier",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "InteriorDesgin",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl157-10001_b__4.jpg?optimize=high&fit=bounds&height=300&width=300&canvas=300:300",
  },
  {
    discontpersentage: "5",
    name: "Home Sizzler 2 Piece Garden",
    price: "5,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/813tzrKnhEL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Home Sizzler 2 Pieces Abstract",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/710sm2Z0HrL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "ARMENIA HAGUE Italian Silk",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/81JMhxmQVZL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Fashion String Polyester",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/81BxuSLkjvL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Fabrilia Floral Net Semi",
    price: "3,200.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/71GB1VL6VwL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Moroccan Motif Eyelet Glace",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/71m2ZxH6JmL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Room Darkening Window Curtain Plain, Black",
    price: "4,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/715Yd3-ZbJL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "OMEMONDE Sun Flower Printed Curtains 7 Feet Door ",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/71DyFVhB0tL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Curtains For Door 8 Feet Long",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/817utKzMJQL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "HIPPO Blackout Indoor Roller Blinds in Roman Style",
    price: "7,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/71G1Wu98fbL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Premium Waterproof Bamboo Roll-up Blinds for Outdoor",
    price: "6,500.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/51Q5df+YiCL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Exporthub 2 Piece Eyelet Polyester Door Curtain Set - 7ft, Red",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/41J3a9TgxDL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Floor Lamp",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Mattressess",
    img: "https://tse1.mm.bing.net/th?id=OIP.XuTOn5MM48Xv7TrD1Ejl5QHaE6&pid=Api&P=0&h=180",
  },
  {
    discontpersentage: "5",
    name: "Industrial Floor Lamp",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Mattressess",
    img: "https://tse2.mm.bing.net/th?id=OIP.5yZfsKmw6fYFbPjyd58ktgAAAA&pid=Api&P=0&h=180",
  },
  {
    discontpersentage: "5",
    name: "Decorative Vase Set",
    price: "2,000.00",
    delivery: "Free Delivery",
    category: "Mattressess",
    img: "https://tse4.mm.bing.net/th?id=OIP.0D-4JgYfJoiio2hyzexXqQHaF5&pid=Api&P=0&h=180",
  },
  {
    discontpersentage: "5",
    name: "Abstract Wall Art",
    price: "5,500.00",
    delivery: "Free Delivery",
    category: "Wallpapers",
    img: "https://sp.yimg.com/ib/th?id=OPAC.HVUm66L7DInetw474C474&o=5&pid=21.1&w=160&h=105",
  },
  {
    discontpersentage: "5",
    name: "Decorative Mirror",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Wallpapers",
    img: "https://sp.yimg.com/ib/th?id=OPAC.WnPOVwd2aY%2bS1Q474C474&o=5&pid=21.1&w=160&h=105",
  },
  {
    discontpersentage: "5",
    name: "Decorative Sculpture",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Wallpapers",
    img: "https://m.media-amazon.com/images/I/61Q8avQbW4L._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Decorative Candle Holder",
    price: "2,500.00",
    delivery: "Free Delivery",
    category: "Customised sofa",
    img: "https://m.media-amazon.com/images/I/71W5BsTqO9L._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern Ceiling Light",
    price: "12,000.00",
    delivery: "Free Delivery",
    category: "Customised sofa",
    img: "https://m.media-amazon.com/images/I/71h2KxLMvUL._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Ceiling Light",
    price: "10,500.00",
    delivery: "Free Delivery",
    category: "Customised sofa",
    img: "https://m.media-amazon.com/images/I/513gHtGJGhL._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Ceiling Light",
    price: "13,800.00",
    delivery: "Free Delivery",
    category: "Customised sofa",
    img: "https://m.media-amazon.com/images/I/513gHtGJGhL._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Ceiling Light",
    price: "15,200.00",
    delivery: "Free Delivery",
    category: "Furnitures",
    img: "https://m.media-amazon.com/images/S/al-eu-726f4d26-7fdb/c269eb9c-ec49-49f4-adeb-ffda0b3d4dec._CR0,357,1500,786_SX507_QL70_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Industrial Ceiling Light",
    price: "14,000.00",
    delivery: "Free Delivery",
    category: "Furnitures",
    img: "https://m.media-amazon.com/images/I/61rqI7d0CmL._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Outdoor Wall Light",
    price: "6,000.00",
    delivery: "Free Delivery",
    category: "Carpets",
    img: "path/to/image36.jpg",
  },
  {
    discontpersentage: "5",
    name: "Outdoor Post Light",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Carpets",
    img: "path/to/image37.jpg",
  },
  {
    discontpersentage: "5",
    name: "Outdoor Hanging Lantern",
    price: "9,500.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "https://aax-eu.amazon.in/x/c/JOM0-m7p2edqqyzN8JtTMQsAAAGRcWBARgMAAAH2AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDEgICDMK3Np/https://www.amazon.in/dp/B08HPJXYBF/?_encoding=UTF8&pd_rd_i=B08HPJXYBF&ref_=sxts_sparkle_sbv&qid=1724184018&pd_rd_w=UdtqJ&content-id=amzn1.sym.df9fe057-524b-4172-ac34-9a1b3c4e647d%3Aamzn1.sym.df9fe057-524b-4172-ac34-9a1b3c4e647d&pf_rd_p=df9fe057-524b-4172-ac34-9a1b3c4e647d&pf_rd_r=E1TF7N2FDJ5QEWCW7T3P&pd_rd_wg=4q7d4&pd_rd_r=7085d254-83b5-4f64-abcd-e2cf5c808f22&pd_rd_plhdr=t",
  },
  {
    discontpersentage: "5",
    name: "Outdoor Path Light",
    price: "5,200.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image39.jpg",
  },
  {
    discontpersentage: "5",
    name: "Outdoor Security Light",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Outdoor Lights",
    img: "path/to/image40.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern Ceiling Fan",
    price: "12,500.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image41.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Ceiling Fan",
    price: "10,800.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image42.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Ceiling Fan",
    price: "13,300.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image43.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Ceiling Fan",
    price: "15,500.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image44.jpg",
  },
  {
    discontpersentage: "5",
    name: "Industrial Ceiling Fan",
    price: "14,800.00",
    delivery: "Free Delivery",
    category: "Ceiling Fans",
    img: "path/to/image45.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern Vanity Light",
    price: "8,000.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image46.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Vanity Light",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image47.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Vanity Light",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image48.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Vanity Light",
    price: "10,500.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image49.jpg",
  },
  {
    discontpersentage: "5",
    name: "Industrial Vanity Light",
    price: "8,800.00",
    delivery: "Free Delivery",
    category: "Vanity Lights",
    img: "path/to/image50.jpg",
  },
  {
    discontpersentage: "5",
    name: "Kind To The Mind (Large, Green, Blue) Clear Glass Chandelier",
    price: "35,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl215-10002_5_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage: "5",
    name: "Mixed Emotions (Large, Chrome, Amber, White) Clear Glass Chandelier",
    price: "28,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl217-10003_10_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage: "5",
    name: "Queen's Necklace (Medium, Rose Gold) Crystal Chandelier",
    price: "40,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl23-10004_3_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage: "5",
    name: "Watch the Throne (Large, Horizontal, Gold) Crystal Chandelier",
    price: "22,500.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10004_01_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage: "5",
    name: "Made In Heaven (Large, Green, White) Glass Chandelier",
    price: "50,000.00",
    delivery: "Free Delivery",
    category: "Chandeliers",
    img: "https://www.whiteteak.com/media/catalog/product/h/l/hl125-10003_1_.jpg?optimize=high&fit=bounds&height=450&width=450&canvas=450:450",
  },
  {
    discontpersentage: "5",
    name: "Industrial Iron Pendant",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image56.jpg",
  },
  {
    discontpersentage: "5",
    name: "Minimalist White Pendant",
    price: "6,800.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image57.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Black Pendant",
    price: "5,600.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image58.jpg",
  },
  {
    discontpersentage: "5",
    name: "Glass Globe Pendant",
    price: "9,200.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image59.jpg",
  },
  {
    discontpersentage: "5",
    name: "Bronze Finish Pendant",
    price: "8,400.00",
    delivery: "Free Delivery",
    category: "Pendants",
    img: "path/to/image60.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Wall Light",
    price: "4,300.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image61.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern LED Wall Light",
    price: "5,000.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image62.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Wall Sconce",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image63.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Wall Lamp",
    price: "6,200.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image64.jpg",
  },
  {
    discontpersentage: "5",
    name: "Art Deco Wall Light",
    price: "7,500.00",
    delivery: "Free Delivery",
    category: "Wall Lights",
    img: "path/to/image65.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern Table Lamp",
    price: "3,200.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image66.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Desk Lamp",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image67.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Table Lamp",
    price: "4,000.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image68.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Table Lamp",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image69.jpg",
  },
  {
    discontpersentage: "5",
    name: "Industrial Desk Lamp",
    price: "3,800.00",
    delivery: "Free Delivery",
    category: "Table Lamps",
    img: "path/to/image70.jpg",
  },
  {
    discontpersentage: "5",
    name: "Modern Floor Lamp",
    price: "7,000.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image71.jpg",
  },
  {
    discontpersentage: "5",
    name: "Classic Floor Lamp",
    price: "6,500.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image72.jpg",
  },
  {
    discontpersentage: "5",
    name: "Rustic Floor Lamp",
    price: "8,200.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image73.jpg",
  },
  {
    discontpersentage: "5",
    name: "Vintage Floor Lamp",
    price: "7,800.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image74.jpg",
  },
  {
    discontpersentage: "5",
    name: "Industrial Floor Lamp",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Floor Lamps",
    img: "path/to/image75.jpg",
  },
  {
    discontpersentage: "5",
    name: "AIRWILL 100% Cotton Solid Pattern Door Curtains Sized,",
    price: "2,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/81HUojux-eL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Tranquebar Curtain Co. 100%",
    price: "2,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/81c3uG7VkIL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Story@Home Blackout",
    price: "3,000.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/71oBn29kgdL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Story@Home Geometric Opaque Blackout Curtains 7 Feet Long Set Of 2 Poly",
    price: "2,800.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/81KlD2GuDpL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: " Polyester Leaf Print Window Curtain (Grey, 5 FEET -150)",
    price: "3,500.00",
    delivery: "Free Delivery",
    category: "Curtain",
    img: "https://m.media-amazon.com/images/I/91z+7RqBs-L._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Deco Window Printed Semi Blackout Roller Blinds for",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/91tjRWJVtTL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "HIPPO 100% Blackout Roller Blinds for Windows UV",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/71tzwve2w0L._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "ABOUT SPACE Bamboo Curtains - W 5 ft x H 6 ft -",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/91teuTXOC4L._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Indoor Sun Shade Telescopic Roller Blind Sun Shield",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/71q9P3a3REL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "MSR 116 Polyester Vertical Blinds/Curtains and Shades for Home",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/41exjQHASJL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    discontpersentage: "5",
    name: "ZEBRA BLINDS Polyester Horizontal Stripes Curtain",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/61CelyGV60L._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Mr.Chickwala Light Filtering & Cooling PVC Exterior ",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/5189vN3SR9L._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "Customize Roller Blinds | HIPPO | Roller Blinds for",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/81j48qtN9ZL._AC_UL320_.jpg",
  },
  {
    discontpersentage: "5",
    name: "ABOUT SPACE Bamboo Curtains - W 4 ft x H 6 ft ",
    price: "9,000.00",
    delivery: "Free Delivery",
    category: "Blinds",
    img: "https://m.media-amazon.com/images/I/91ODp98rl+L._AC_UL320_.jpg",
  },
  
];

const categoryDetails = ({ category }) => {
  const { name } = useParams();

  const selectname = category || name;

  const filteredProducts = products.filter(
    (product) => product.category.toLowerCase() === selectname.toLowerCase()
  );
  // Add more categories as needed

  return (
    <div>
      {name ? (
        <>
          <CategoryBanner title="Our Products" />
          <Chandeliers name={selectname} />{" "}
        </>
      ) : null}

      <ShowCategoryWise products={filteredProducts} />
      {/* <ShowCategoryWise title="Pendants" products={pendants} />
        <ShowCategoryWise title="Wall Lights" products={wallLights} /> */}
      {/* Add more categories as needed */}
    </div>
  );
};

export default categoryDetails;
